name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: MatangoTest.testSuffix
      id: matangotest-testsuffix
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: MatangoTest.testSuffix
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "MatangoTest.testSuffix"
        timeout: 10
        max-score: 5
    - name: MatangoTest.testCirculation
      id: matangotest-testcirculation
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: MatangoTest.testCirculation
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "MatangoTest.testCirculation"
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MATANGOTEST-TESTSUFFIX_RESULTS: "${{steps.matangotest-testsuffix.outputs.result}}"
        MATANGOTEST-TESTCIRCULATION_RESULTS: "${{steps.matangotest-testcirculation.outputs.result}}"
      with:
        runners: matangotest-testsuffix,matangotest-testcirculation
